CREATE TABLE IF NOT EXISTS notification (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL COMMENT '接收用户ID',
    biz_type VARCHAR(50) NOT NULL COMMENT '业务类型',
    biz_id INT NOT NULL COMMENT '业务ID',
    title VARCHAR(100) NOT NULL COMMENT '标题',
    content VARCHAR(255) NOT NULL COMMENT '内容',
    is_read TINYINT NOT NULL DEFAULT 0 COMMENT '0未读 1已读',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通知表';
